### PR TITLE
Support :ref:, :numref: and conf.py customizations

### PR DESCRIPTION
**Pull request by HFriberg-mosek**
I took up the challenge and succeeded enabling references via :numref: and :ref: to theorems. I have not touched the other directives as I do not use them, and for the same reason added 4 configuration parameters to enable/disable features via conf.py.

### CODE REVIEW

**Comment by rpuntaie** [comment]
add_fignumber() in visit_thm_html has no effect. Do you have an idea how to populate self.builder.fignumbers?

**Comment by rpuntaie** [comment]
got it: needs numfig=True in conf.py
I will changed it to show at least the caption if there is no numbering.

**Comment by rpuntaie** [comment]
added thm_no_dispname, to configure display of theorem name

**Comment by HFriberg-mosek** [comment]
Not sure I understand the usecase for `thm_no_dispname`. Don't you get the same effect by registering a theorem with no displayname, e.g.,
`
('assumption', '', 'assumption'),
`
and this with a per environment choice?

**Comment by rpuntaie** [comment]
You are basically right. But by uncommenting just one line one can switch more easily than by editing more lines in ~/conf.py. And you still can do the latter if you want to.
It is like with the config values you introduced:
They are not needed, but don't do any harm, either.
I've updated pypi. Thank you for the pull request.

**Pull request merged**
